services:
  web:
    volumes:
      - ../../clients/web:/app
      - /app/node_modules
      - /app/.next

  api:
    volumes:
      - ../../services/api:/app
      - /app/node_modules
      - /app/dist
